services:
  web:
    build:
      context: .
      target: ${TARGET:-base}
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.nuxt
      - /app/.output
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - HOST=0.0.0.0
    command: sh -c "bun install && ${COMMAND:-bun run dev}"
